# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost

development:
  <<: *default
  database: project_tracker
  username: tracker_dbuser
  password: "lmkYIYbC"

production:
  <<: *default
  database: project_tracker
  username: tracker_dbuser
  password: "lmkYIYbC"

test:
  <<: *default
  adapter: mysql2
  database: project_tracker_test
  username: test_dbuser
  password: "EP2cWIQS"
